"""Unification acceptance: ONE shared recall universe across engines.

Same bank FILE is necessary but not sufficient. This proves, through the
REAL code paths on both sides with no restarts between writes and reads:

- hermes provider write  ->  omp backend (Mnemopi facade) recall finds it
- omp backend remember   ->  hermes provider prefetch finds it
  (including an omp session-scoped row: the shared universe is not
  partitioned by writer session)

The omp side runs in a separate bun process (WAL write-visibility without
restart). Only the native math kernels get working JS fallbacks via
``mock.module`` (no Rust toolchain in test envs); every other native
export is an inert dummy, so anything the FTS-only path actually CALLS
would throw loudly. FTS SQL, schema, and fusion are the production omp
path. Pinned Mercury posture on both sides: bank ``default``, global
scoping, FTS-only (``noEmbeddings``).

Skips cleanly when bun or the omp workspace install is unavailable.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

# Pinned identity on BOTH sides (directive: identical bank name, no
# per-project sibling banks, global scoping, both FTS-only).
BANK_NAME = "default"

BUN_MATH_NAMES = frozenset({"mmrRerankIndices", "cosineSimilarityPairs", "vectorIndexTopK"})

BUN_BODY = """const { Mnemopi } = await import(OMP_SRC);
const dbPath = process.env.MNEMOPI_BANK;
if (!dbPath) throw new Error("MNEMOPI_BANK env required");

function openBackend() {
\treturn new Mnemopi({
\t\tdbPath,
\t\tbank: "default",
\t\tsessionId: "omp-roundtrip",
\t\tnoEmbeddings: true,
\t\treconcile: false,
\t});
}

test("omp recalls hermes-written row", async () => {
\tconst m = openBackend();
\ttry {
\t\tconst hits = await m.recall("pomegranate 3344", 5);
\t\texpect(hits.map(h => h.content).join("\\n")).toContain("3344");
\t} finally {
\t\tm.close();
\t}
});

test("omp remember is hermes-recallable", async () => {
\tconst m = openBackend();
\ttry {
\t\tconst id = m.remember("omp wrote persimmon row 5566", { source: "conversation" });
\t\texpect(typeof id).toBe("string");
\t} finally {
\t\tm.close();
\t}
});
"""


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _native_export_names() -> list:
    """Every export of the pi-natives JS surface (for the test stub)."""
    index_js = _repo_root() / "omp" / "packages" / "natives" / "native" / "index.js"
    names = []
    for line in index_js.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("export const "):
            names.append(line[len("export const "):].split()[0])
    return names


def _bun_test_source() -> str:
    """Bun test driving the REAL omp backend with natives stubbed."""
    math_stubs = (
        "\tmmrRerankIndices: (contents, _scores, _lambda, limit) =>\n"
        "\t\tcontents.map((_, i) => i).slice(0, limit),\n"
        "\tcosineSimilarityPairs: () => [],\n"
        "\tvectorIndexTopK: () => [],\n"
    )
    dummies = "".join(
        "\t%s: __Dummy,\n" % name
        for name in _native_export_names()
        if name not in BUN_MATH_NAMES
    )
    lines = [
        "// Generated by test_mnemosyne_unification.py. REAL omp backend path",
        "// (Mnemopi facade -> BeamMemory) with only native math kernels stubbed.",
        'import { mock, test, expect } from "bun:test";',
        "",
        "const OMP_SRC = process.env.MNEMOPI_SRC;",
        'if (!OMP_SRC) throw new Error("MNEMOPI_SRC env required");',
        "",
        "class __Dummy {}",
        "",
        'mock.module("@oh-my-pi/pi-natives", () => ({',
        math_stubs.rstrip("\n"),
        dummies.rstrip("\n"),
        "}));",
        "",
        BUN_BODY,
    ]
    return "\n".join(lines)


def _omp_backend_ready() -> str:
    """Return skip reason, or '' when the real omp path can run."""
    if shutil.which("bun") is None:
        return "bun not on PATH"
    root = _repo_root()
    src = root / "omp" / "packages" / "mnemopi" / "src" / "core" / "memory.ts"
    if not src.is_file():
        return "omp source missing: %s" % src
    if not (root / "omp" / "node_modules").is_dir():
        return "omp workspace not installed (bun install)"
    return ""


def _new_provider(monkeypatch, tmp_path, session="unify-sess"):
    from plugins.memory.mnemosyne import MnemosyneMemoryProvider

    monkeypatch.setenv("MERCURY_HOME", str(tmp_path))
    monkeypatch.setenv("MNEMOSYNE_DB_PATH", "")
    bank = str(tmp_path / "memories" / "mnemopi.db")
    provider = MnemosyneMemoryProvider()
    provider.initialize(session, mercury_home=str(tmp_path), agent_context="primary")
    assert provider._bank_path == bank
    return provider, bank


def test_shared_universe_round_trip(tmp_path, monkeypatch):
    reason = _omp_backend_ready()
    if reason:
        pytest.skip(reason)

    provider, bank = _new_provider(monkeypatch, tmp_path)
    # hermes -> bank (fresh connection each op; no restart anywhere below).
    provider.on_memory_write("add", "memory", "hermes wrote pomegranate row 3344 for omp recall")
    provider.shutdown()

    bun_test = tmp_path / "unify.test.ts"
    bun_test.write_text(_bun_test_source(), encoding="utf-8")
    env = {
        **os.environ,
        "MNEMOPI_SRC": str(
            _repo_root() / "omp" / "packages" / "mnemopi" / "src" / "core" / "memory.ts"
        ),
        "MNEMOPI_BANK": bank,
    }
    proc = subprocess.run(
        ["bun", "test", str(bun_test)],
        cwd=str(_repo_root() / "omp" / "packages" / "mnemopi"),
        capture_output=True, text=True, timeout=300, env=env,
    )
    assert proc.returncode == 0, "bun round-trip failed:\n%s\n%s" % (
        proc.stdout[-2000:], proc.stderr[-2000:])

    # omp -> hermes: fresh provider instance (no shared state, no restart).
    # The bun side wrote with default session scope; the shared universe
    # must still surface it.
    provider2, _ = _new_provider(monkeypatch, tmp_path, session="other-sess")
    found = provider2.prefetch("persimmon omp wrote")
    assert "5566" in found
    provider2.shutdown()


def test_bun_stub_covers_native_surface():
    """The stub must name every native export (linkage is static)."""
    root = _repo_root()
    if not (root / "omp" / "packages" / "natives" / "native" / "index.js").is_file():
        pytest.skip("omp tree unavailable")
    src = _bun_test_source()
    for name in _native_export_names():
        assert re.search(r"\b%s\b" % re.escape(name), src), name
